name: modu_tour
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^0.5.1
  firebase_analytics: ^6.1.0
  firebase_database: ^4.2.0
  firebase_messaging: ^7.0.3
  firebase_admob: ^0.10.2
  http: ^0.12.2
  sqflite: ^1.3.2
  path:  ^1.7.0
  shared_preferences: ^0.5.12
  crypto: ^2.1.5
  google_maps_flutter: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - repo/images/map_location.png

