name: listview_example
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - repo/images/bee.png
    - repo/images/cat.png
    - repo/images/cow.png
    - repo/images/dog.png
    - repo/images/fox.png
    - repo/images/monkey.png
    - repo/images/pig.png
    - repo/images/wolf.png